trigger:
- '*'

pool:
  name: "Azure Pipelines"

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: "Azure Pipelines"
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
    
- stage: tests
  displayName: Tests

- stage: Release
  displayName: Release
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment:
    displayName: Release
    pool:
      name: Default
    