trigger:
- '*'

pool:
  vmImage: 'windows-latest'

stages:
- stage: build
  displayName: Build

  jobs:
  - job: Build
    pool:
      pool:
        vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'

    